sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
language: node_js
cache: yarn
node_js:
  - "node"
  - "6"
  - "5"
script:
- npm test
